# conf/model/base.yaml
model_type: nhits_qra
size: base
plot_size: base
input_size: ${data.context_length}
h: ${data.forecast_horizon}

n_blocks: [3, 3, 3]
mlp_units:
  - [512, 512]
  - [512, 512]
  - [512, 512]
dropout_prob_theta: 0.1
n_pool_kernel_size: [8, 4, 2]
n_freq_downsample: [8, 4, 2]

past_unknown_cov_cutoff: 14
realistic_mode: true