model_type: normalizing_flows
size: base
plot_size: base
tf_in_size: 256
nf_hidden_dim: 256
n_layers: 16
n_heads: 8
n_flow_layers: 20
n_made_blocks: 3
tf_dropout: 0.1
enc_unknown_cutoff: 14
dec_known_past_injection_horizon: 12
realistic_mode: true