# order here defines channel order in feat_dynamic_real
use_covariates: true
ck_cols:
  - is_weekend
  - is_holiday
  - month_sin
  - month_cos
  - day_of_week_sin
  - day_of_week_cos
  - hour_sin
  - hour_cos
cu_cols: []